### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by egeerardyn** [brunocvcunha/awesome-userscripts#1]
As a response to https://github.com/sindresorhus/awesome/pull/672#issuecomment-228603265

I have a few comments regarding what I think is missing in this list:

 - for ALL major browsers, you can list where you can get the userscript manager (e.g. I am using Safari most of the time, others might be using IE/Edge, perhaps some people are using Opera, Vivaldi, Maxthon, ...)
 - I think it's really strange that you don't even link back to userscripts.org
 - There are quite some interesting scripts for GitHub as well (e.g. Monospaced edit fields, commit line limits, ...), those are ones that many people could benefit from

**Comment by bvolpato** [comment]
All improvements were completed, thank you!
